### ISSUE TITLE
Star Citizen 3.20 .Skin Files failing to export

### ISSUE THREAD

**Issue by Baconator650** [Markemp/Cryengine-Converter#168]
Star Citizen 3.20 .Skin Files (specifically landing gear) failing to export

**Comment by Baconator650** [comment]
Also appears that .chr files fail to extract as well.

**Comment by Markemp** [comment]
Was this working on earlier versions?

**Comment by Baconator650** [comment]
It's a change in the ivo format.

There has been a lot of back and forth on versions working. But before 3.20 (using 3.19) we were able to convert the .skin files with 1.3.1 of the CGF-Converter with out issue and preserving the material naming convention that some use in their workflows.

**Comment by Markemp** [comment]
Still working on getting animations working.  Sorry this is taking so long.  It's been a blocker for a few months now.

**Comment by Markemp** [comment]
This may not be so bad.  Preliminarily it looks like he only gave new chunk type numbers for the objects. Testing a solution today and may have a preliminary 1.6 posted for those who want to use the 3.20/3.21 files

**Comment by Markemp** [comment]
Hmm... maybe it won't be so easy after all.  Old on left, new is the bone garbage on the right.

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/3faa3c41-eb81-45ef-ba22-1d60d121f3ab)

**Comment by Baconator650** [comment]
Oh, thats a big difference. Have you tried experimenting with some of the landing gear?

**Comment by Markemp** [comment]
I take it back. I think I got it.  I just forgot to handle the materials, so it failed spectacularly.  I'll try the landing gear next.  Have any in particular you want tested?

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/49e15ce1-1022-4878-b2a7-bbc32f84b9eb)

**Comment by Baconator650** [comment]
I have been using the AEGS_Gladius as my testing model as I can look at legacy stuff to compare it too. But for the new stuff probably the new Crusader A1/C1 would be a good test for a newer ship.

**Comment by Markemp** [comment]
Gladius landing gear.  Armature is there too.

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/fc0da807-3766-40a7-b2a3-edb2418c030f)

I'm having some problems getting the texture paths to output properly, so working on cleaning that up.  Shouldn't be much longer.

**Comment by Baconator650** [comment]
> Gladius landing gear. Armature is there too.
> 
> 
> 
> I'm having some problems getting the texture paths to output properly, so working on cleaning that up. Shouldn't be much longer.


Looking good!! To maybe save you some time, both Blender and 3DS Max users use specialized scripts to handle Star Citizen's complex and varied materials and only require the naming convention of the material to be like "lowtech_alpha_ext_a_mtl_graphical_tint_decal_a".

**Comment by Markemp** [comment]
![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/0e46030e-ef77-4bc5-8f11-ed8e4b8c69ca)

Is it supposed to be `-mtl-` or `_mtl_`?

**Comment by Baconator650** [comment]
> ![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/0e46030e-ef77-4bc5-8f11-ed8e4b8c69ca)
> 
> 
> 
> Is it supposed to be `-mtl-` or `_mtl_`?

The later

_mtl_

**Comment by Markemp** [comment]
Got it.  The latest version of the branch should name the materials correctly now.  

I'm close to doing a 1.6 release, so if you can find any bugs that need addressing or some updates, let me know.  Thanks!

**Comment by Almightykitten** [comment]
So I compiled the current repository and it just converts to the folder that is navigated in powershell, and not were the source files are.

**Comment by Markemp** [comment]
> So I compiled the current repository and it just converts to the folder that is navigated in powershell, and not where the source files are.

I'm not sure I follow.  Converts what to the folder?

**Comment by Baconator650** [comment]
> > So I compiled the current repository and it just converts to the folder that is navigated in powershell, and not where the source files are.
> 
> 
> 
> I'm not sure I follow.  Converts what to the folder?

Having the same issue was batch converting. The collada files are being placed in the folder in which powershell is opened in, not the same folder where the .cgf, .cga, .skin

**Comment by Markemp** [comment]
Err... that's not good.  Can you show the commands you are running when that happens?

**Comment by Almightykitten** [comment]
Another thing it ignores the path for the mtl in the cga/cgf/skin file if it has .mtl at the end of it, so you don't get the actual material names in the converted dae.
This be a problem for older files.

**Comment by Markemp** [comment]
Ok, thanks for the info.  I'll take a look at it and see if I can figure out what broke.  Sorry about that!

**Comment by Markemp** [comment]
Was this working on a recent commit?  Can you help me pinpoint the time it stopped working?

**Comment by Almightykitten** [comment]
reckon its the function Path.GetFileNameWithoutExtension
from [commit](https://github.com/Markemp/Cryengine-Converter/commit/8a8d68cc42dc1aa3197d531cdefc1c0d4ca89d72)

**Comment by Markemp** [comment]
Pushed up a new commit that I'm hoping fixes these issues.  Can you test them out and let me know?

**Comment by Baconator650** [comment]
Think it might be a problem with how I am compiling it, but I have been getting this.

![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/aee49efa-42c4-49e9-b644-7b319c1cfc7d)

**Comment by Baconator650** [comment]
Think it might be a problem with how I am compiling it, but I have been getting this.

![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/d09e7355-a711-4ba1-8274-d3ee4c5eb164)

**Comment by Baconator650** [comment]
And this...
![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/df029d6e-b024-49a7-9ab7-bf8f4d81308c)

**Comment by Markemp** [comment]
Hm... the material name is a problem.  Something like `-material-27` means it couldn't find the material file.  Are these 3.20 or 3.22 files?  I haven't downloaded the latest version yet.

**Comment by Markemp** [comment]
![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/07d64e8c-fba6-43d1-bb55-d2cd2259ec59)
This is v3.21.

**Comment by Baconator650** [comment]
3.22 files

**Comment by Markemp** [comment]
Ok, let me download them and take a look.  I'm preparing an angry fax to send Ivo in the meantime.

**Comment by Markemp** [comment]
Here's the CRUS Spirit:

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/46f23807-70f0-43eb-939f-7b1328bc1367)

Can you build again and see if it's working?  Not sure why it failed.

**Comment by Baconator650** [comment]
I think it's a user error on my part on building and publishing it to an exe.

**Comment by Baconator650** [comment]
![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/62b701eb-04db-403a-acee-e9b639558351)
 
Found the issue causing the errors. User error using StarFab, exported the mtl in a json format (needed for Max scripts to create materials). Switched the export to a CryXMLB format and it worked (StarFab json and xml format do not work).

Looks like the bone placement for the landing gear is off, I believe this was an issue before though.

**Comment by Baconator650** [comment]
Its looking like the latest commits has broken bone structure to leave only a single bone.

When playing around with the landing gear before the commit, it looks like the rotations aren't being applied.

![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/ead0c687-4a10-46cf-beb9-3c04dad06e61)

**Comment by Markemp** [comment]
I found the issue with it only creating the root bone, and will push up a fix here in a few minutes:
![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/4bd5d6d7-d403-435e-b703-7fda0ebb4c76)

Still cleaning up some material handling stuff, but almost have that part done.  Then ... not sure what next.  I'll go through the issues list and make sure as much stuff is solved as possible.

**Comment by Emygdious** [comment]
Still having issues with .skin files not sure if a fix is still being worked on currently or not.

![PS Error](https://github.com/Markemp/Cryengine-Converter/assets/71308026/4bbba4db-52f3-4655-b940-e1f9ff3faac5)

**Comment by Markemp** [comment]
Yup, still working on a 1.6 release.  I'm fixing up some material issues right now.  Until that is complete, the new SC skin files will have problems.  Sorry for the time it is taking on this.

**Comment by Baconator650** [comment]
Don't forget to look at the rotations for SC files too

**Comment by Markemp** [comment]
Got the materials refactored (again).  Should support multiple material files, which is something I've only seen in Archeage models so far, but it needed to be done.

Arclight pistol parts are working in this build too.
![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/e62b0fba-c5d0-43cd-9ebe-b47777acff6b)

@Baconator650 , can you check the landing gears too?  I think they are working but just want to make sure.

**Comment by Baconator650** [comment]
Materials are good.
Geometry is outputting.

Position and Rotations are substantially off:
![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/35246218-c3a0-4b38-9aff-6b3437e02411)

Comparing it with an older extraction [Correct Position, somewhat correct rotations], it appears to be rotated 180 degrees as well.

![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/1ebebdff-160a-485f-9adf-4420d84a15e1)
It appears to be just the bones/skeleton that are off
![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/4692858c-9784-49b0-9f48-1fe8ef607def)


Overall CGF-Convert rotations are good, but they don't match up with what the animation files export out as from Cry Engine. This usually requires a quick fix with rotation of the **pivot points** by [90,00,00] on then [00,90,00] via a local rotation. Here is a comparison with a normal CGA file. 

[done with the last tweaks from 2/6/2024][all displayed rotations are world reference]
_will add image soon_

[Done with an older CGF-Converter Build from an older SC build][all displayed rotations are world reference]
![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/28ec1441-501a-474c-a3ee-82d3217c5385)


(CC=CGF Converter; HTR=HTR animation file export from Dymek CryEngine reading a SC3,8.2 build)

**Comment by Baconator650** [comment]
Collada (.dae), it's what StarFab deals with.

**Comment by Markemp** [comment]
Got it.  Found the seat and it does look like it's moved down instead of I'm assuming up.

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/826c1838-3b04-40d3-ba4f-3d732a4d7d11)

What landing gear is that?

**Comment by Baconator650** [comment]
Should be the front landing gear of the Hurricane.

**Comment by Markemp** [comment]
Here is the ANVL Hurricane front landing gear CHR and SKIN files.  The CHR definitely is not matching up with the skin bones.  I'm looking into that now.
![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/367f38fd-b75c-4b54-bc01-e0701f5d8ae6)

I think the animation files are referencing the chr files?  Are you pairing them up as part of the process?

**Comment by Baconator650** [comment]
The Cry Engine Character Tool is what I am using to extract the animations, which uses these .cdf and .chr.chrparams

![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/fe6671af-ae9d-4252-8be7-04a08a1e1155)

![image](https://github.com/Markemp/Cryengine-Converter/assets/78010776/a2b69732-728f-4020-be5d-213e75c18fea)

Unfortunately due to CiG TOS, I can't not publicly post Star Citizen files.

**Comment by Markemp** [comment]
Oh, I already have the game files. I'm just looking for the working Collada file.

Or can you tell me if it was made with the 1.5 converter or some intermediate build?

**Comment by Markemp** [comment]
I'm definitely seeing differences in the front landing gear skin and chr files between the 1.3.1 version and the 1.6 version, in the node hierarchy and the controllers.  Just to verify, the 1.3.1 version matches up correctly with the animation cdf/chrparams files, and the 1.6 one doesn't?

This could also explain why I could never get the animations to work with the 1.6 stuff either. :(

**Comment by Baconator650** [comment]
No, nothing has ever matched correctly out of the box. they always need their rotations readjusted. 

But I haven't experimented with loading a skin file first and then replacing it with a chr skeleton.

**Comment by Emygdious** [comment]
@Markemp I still get the same error when trying to export the skin files for the arclight pistol. Using v1.6 of the converter

https://gyazo.com/fc955268a4a5c2655c7362bf77fa6bed

**Comment by Markemp** [comment]
Are you using the -objectdir argument?  For Ivo models right now (especially when it can't find the material file or the material file isn't added as an arg), it's throwing an error when creating default materials.

**Comment by Markemp** [comment]
@Baconator650 I think I figured out the CHR files! 
![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/56635a66-2a30-4bf3-acc7-a0de920fc892)

You may be able to use the animation files directly with the CHR models now.  🤞🏽 Going to do a little more testing and push up the changes in a few minutes.

**Comment by Emygdious** [comment]
> Are you using the -objectdir argument? For Ivo models right now (especially when it can't find the material file or the material file isn't added as an arg), it's throwing an error when creating default materials.

Yes I am using that argument. The reason I'm trying to export the skin file is before the normal cgf file that is converted is missing half of the geometry and someone who helped me out told me the rest of the geometry is in the skin files? Not sure if that's 100% accurate or not.

**Comment by Markemp** [comment]
I just ran this command against the directory with the pistol files:

`foreach ($file in (Get-ChildItem *.cga,*.cgf,*.chr,*.skin)) { cgf-converter.exe $file -objectdir d:\depot\sc3.22\data }`

There are 4 files (I removed all the LOD ones), but since 2 of the files have the same name (one cga, one cgf), whatever is run last is the dae file that is left.

All you really need to do is convert the cga, chr and skin files.  The cgf one is usually the same as the cga, but without controller information.  Are you trying to convert one of the geometry files (cgam, skinm)?

Here's the pistol with the skeleton, body and parts:
![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/a3fb8d17-0b57-4e35-a65e-5975423e86c4)

**Comment by Baconator650** [comment]
> @Baconator650 I think I figured out the CHR files! 
> 
> ![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/56635a66-2a30-4bf3-acc7-a0de920fc892)
> 
> 
> 
> You may be able to use the animation files directly with the CHR models now.  🤞🏽 Going to do a little more testing and push up the changes in a few minutes.

We are looking pretty good, but not perfect, I am still needing to apply adjustments to the rotations that I have been previously doing. But I am questioning my animation source as I am pulling data from SC 3.8 and it's going the Dymeks Cry Engine and then exporting it out to an HTR format. If I remember correctly CryEngine exported FBX files kinda wonky. 

Out of curiosity, you mention playing around with SC animation. Are you using the limited .caf files that are available in the current build, an older build? Or using an extraction tool that is different then StarFab?

**Comment by Markemp** [comment]
I've been working with an animation file (dba) for MechWarrior Online trying to get it to work.  At least .chr files with no geometry seem to be working now, but still no luck on the animations.  The converter is looking for a chrparams file that goes with a chr file, then finds the associated animation file (just dba right now, not caf ones).  It would be nice to have all the animations for an armature to be natively included in the Collada file, but no luck.

**Comment by Baconator650** [comment]
Hearing reports that 3.23 SC build is causing issues with landing gear again.

In regards to animations, any chance we could have have the associated files converted out of ivo to a standard CryEngine format so we can use previously established methods.

**Comment by Markemp** [comment]
Closing issue as this seems to be pre-3.24 issues.  Should all be resolved now, or at least when 1.7.0 comes out.
